### ISSUE TITLE
Cannot use COM object "Microsoft.Update.AutoUpdate" in Boxstarter

### ISSUE THREAD

**Issue by C-Duv** [mwrock/boxstarter#108]
I am using *Boxstarter* to build a defined *Windows* environment (both softwares and *Windows* configuration).

I wanted to configure *Windows Update* to "Notify before installation".
I have found the following PowerShell snippet:
```PowerShell
$WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
$WindowsUpdateSettings.NotificationLevel = 3
    # Possible values for "NotificationLevel":
    # 0 = Not configured
    # 1 = Disabled
    # 2 = Notify before download
    # 3 = Notify before installation
    # 4 = Scheduled installation
$WindowsUpdateSettings.save()
```

Which works just fine on a Administrator's PowerShell:
```
PS C:\Windows\system32> $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
PS C:\Windows\system32> $WindowsUpdateSettings.NotificationLevel = 3
PS C:\Windows\system32> $WindowsUpdateSettings.save()
```

But fails when used in a Boxstarter Package:
```
Boxstarter Version 2.5.21
(c) 2015 Matt Wrock. http://boxstarter.org

Boxstarter: Disabling Automatic Updates from Windows Update
+ Boxstarter starting Calling Boxstarter's vendored Chocolatey to install MyPackage. This may take several minutes to complete...
Chocolatey (v0.9.8.33) is installing 'MyPackage' and dependencies. By installing you accept the license for 'MyPackage' and each dependency you are installing.

MyPackage v1.0.0
Write-Error : MyPackage did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] System.Management.Automation.RuntimeException: Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037" ---> System.Management.Automation.SetValueInvocationException: Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037" ---> System.Runtime.InteropServices.COMException (0x80240037): Exception from HRESULT: 0x80240037
   --- End of inner exception stack trace ---
   at System.Management.Automation.Adapter.BasePropertySet(PSProperty property, Object setValue, Boolean convert)
   at System.Management.Automation.PropertyReferenceNode.SetValue(PSObject obj, Object property, Object value, ExecutionContext context)
   --- End of inner exception stack trace ---
   at System.Management.Automation.PropertyReferenceNode.SetValue(PSObject obj, Object property, Object value, ExecutionContext context)
   at System.Management.Automation.AssignablePropertyReference.SetValue(Object value, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
-----------------------
At C:\Users\user\AppData\Roaming\Boxstarter\Chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:14
+   Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

MyPackage has finished successfully! The chocolatey gods have answered your request!
Added C:\ProgramData\chocolatey\bin\certutil.exe shim pointed to 'c:\programdata\chocolatey\lib\mypackage.1.0.0\binaries\nss_3.12.7_tools\certutil.exe'.
Finished installing 'MyPackage' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
+ Boxstarter finished Calling Boxstarter's vendored Chocolatey to install MyPackage. This may take several minutes to complete... 00:00:11.1792320
True
PS C:\Windows\system32>
```

Package installation was ran from a non-elevated console but Boxstarter did asked for elevation ("Boxstarter: User is not running with administrative rights. Attempting to elevate...") and the rest of the process was ran in the elevated console.

Why both behaviour differs? Is there a workaround?

I am using Windows 7 Pro 64-bits and Boxstarter v2.5.21.

**Comment by mwrock** [comment]
I have not been able to reproduce this. Here is what I have done:
 - Created a package with these contents:
```
Write-host "setting NotificationLevel to 3"
try {
    $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
    $WindowsUpdateSettings.NotificationLevel = 3
    $WindowsUpdateSettings.save()
    Write-host "setting NotificationLevel to 3 - Done!!"
}
finally {
    $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
    Write-host "setting NotificationLevel to $($WindowsUpdateSettings.NotificationLevel) - Done!!"
}
```
 - Package is named test-package
 - Installed the package:
```
Install-BoxstarterPackage -PackageName test-package -DisableReboots
```
Here is the output:
```
Boxstarter: Installing package test-package
Boxstarter Version 2.5.21
(c) 2015 Matt Wrock. http://boxstarter.org

Boxstarter: Disabling Automatic Updates from Windows Update
+ Boxstarter starting Calling Boxstarter's vendored Chocolatey to install test-package. This may take several minutes to complete...
Chocolatey (v0.9.8.33) is installing 'test-package' and dependencies. By installing you accept the license for 'test-package' and each dependency you are installing.

test-package v2.5.23
setting NotificationLevel to 3
setting NotificationLevel to 3 - Done!!
setting NotificationLevel to 4 - Done!!
Finished installing 'test-package' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
+ Boxstarter finished Calling Boxstarter's vendored Chocolatey to install test-package. This may take several minutes to complete... 00:00:05.2296144
Boxstarter: Enabling Automatic Updates from Windows Update


Errors       : {}
ComputerName : localhost
Completed    : True
FinishTime   : 09/09/2015 21:12:26
StartTime    : 09/09/2015 21:12:20
```
I'm using windows 10.

Oddly the value does not seem to persist as seen in the output. The same occurs when running right off the command line.

If you could provide the exact repro steps you are using, that would be really helpful!

**Comment by C-Duv** [comment]
I almost got your code running without error...

Here what I've done:
```PowerShell
New-BoxstarterPackage -Name Issue-108-test -Description "Test package to debug Issue #108"
```

Content of `Issue-108-test\tools\ChocolateyInstall.ps1` file is:
```PowerShell
Write-host "setting NotificationLevel to 3"
try {
    $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
    $WindowsUpdateSettings.NotificationLevel = 3
    $WindowsUpdateSettings.save()
    Write-host "setting NotificationLevel to 3 - Done!!"
}
finally {
    $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
    Write-host "setting NotificationLevel to $($WindowsUpdateSettings.NotificationLevel) - Done!!"
}
```

```PowerShell
Invoke-BoxstarterBuild Issue-108-test
Install-BoxstarterPackage -PackageName Issue-108-test -DisableReboots
```

Output is:

	Boxstarter: Installing package Issue-108-test
	Boxstarter Version 2.5.21
	(c) 2015 Matt Wrock. http://boxstarter.org

	Boxstarter: Disabling Automatic Updates from Windows Update
	+ Boxstarter starting Calling Boxstarter's vendored Chocolatey to install Issue-108-test. This may take several minutes to complete...
	Chocolatey (v0.9.8.33) is installing 'Issue-108-test' and dependencies. By installing you accept the license for 'Issue-108-test' and each dependency you are installing.

	Issue-108-test v1.0.0
	setting NotificationLevel to 3
	setting NotificationLevel to 1 - Done!!
	Write-Error : Package 'Issue-108-test v1.0.0' did not install successfully: Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037"
	At C:\Users\C-Duv\AppData\Roaming\Boxstarter\Chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:28
	+                 Write-Error <<<<  "Package `'$installedPackageName v$installedPackageVersion`' did not install successfully: $($_.Exception.Message)"
		+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
		+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

	Finished installing 'Issue-108-test' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
	Write-Error : Chocolatey reported an unsuccessful exit code of 1
	At line:124 char:32
	+                     Write-Error <<<<  "Chocolatey reported an unsuccessful exit code of $LastExitCode"
		+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
		+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

	+ Boxstarter finished Calling Boxstarter's vendored Chocolatey to install Issue-108-test. This may take several minutes to complete... 00:00:09.8999736
	Boxstarter: Enabling Automatic Updates from Windows Update


	Completed    : True
	Errors       : {Chocolatey reported an unsuccessful exit code of 1, Package 'Issue-108-test v1.0.0' did not install successfully: Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037", Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037"}
	ComputerName : localhost
	StartTime    : 10/13/2015 15:15:42
	FinishTime   : 10/13/2015 15:15:56

I also confirm the settings done by this BoxStarter package are not persistent whereas the following (Administrator's PowerShell) are totally working (confirmed by looking at the GUI):

```PowerShell
PS C:\Windows\system32> $WindowsUpdateSettings = (New-Object -ComObject "Microsoft.Update.AutoUpdate").Settings
PS C:\Windows\system32> $WindowsUpdateSettings.NotificationLevel = 3
PS C:\Windows\system32> $WindowsUpdateSettings.save()
```

I am using Windows 7 SP1 Professional (64-bits)

**Comment by mwrock** [comment]
Odd. All I can surmise is that it is win7 sp1 specific.

**Comment by C-Duv** [comment]
In case of any use, I get the same thing on a Windows 8.1 Professionnal (64-bits):

    D:\Boxstarter>BoxStarter.bat Issue-108-test -DisableReboots
    Boxstarter: Installing package Issue-108-test
    Boxstarter Version 2.5.21
    (c) 2015 Matt Wrock. http://boxstarter.org
    
    Boxstarter: Disabling Automatic Updates from Windows Update
    + Boxstarter starting Calling Boxstarter's vendored Chocolatey to install Issue-108-test. This may take several minutes to complete...
    Chocolatey (v0.9.8.33) is installing 'Issue-108-test' and dependencies. By installing you accept the license for 'Issue-108-test' and each dependency you are installing.
    
    Issue-108-test v1.0.0
    setting NotificationLevel to 3
    Write-Error : Package 'Issue-108-test v1.0.0' did not install successfully: Exception setting "NotificationLevel": "Exception from HRESULT: 0x80240037"
    At D:\Boxstarter\Chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:17
    +                 Write-Error "Package `'$installedPackageName v$installedPackageV ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error
    
    Finished installing 'Issue-108-test' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
    Write-Error : Chocolatey reported an unsuccessful exit code of 1
    At line:124 char:21
    +                     Write-Error "Chocolatey reported an unsuccessful exit code o ...
    +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error
    
    + Boxstarter finished Calling Boxstarter's vendored Chocolatey to install Issue-108-test. This may take several minutes to complete... 00:00:29.0974539
    True
    Boxstarter: Enabling Automatic Updates from Windows Update
    
    D:\Boxstarter>

**Comment by C-Duv** [comment]
Just tested and I still have the issue on Boxstarter v2.8.29.
One thing we didn't checked is the PowerShell version: I am running 2.0 (on Windows 7 SP1)
