### ISSUE TITLE
WebInstaller not working

### ISSUE THREAD

**Issue by Proxx** [mwrock/boxstarter#139]
Since the updated version of the webinstaller i get an error

this occurs both on windows 10 and windows 7 as far as i tested.
i tried a Dutch OS, English OS and German OS

When investigating the logs i found this.
I think the problem should be fairly easy to solve:
```
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1 resulted in exception. Following failure messages were detected:
		+ File, chocolatey.dll, has a different computed hash than specified in manifest.
```
**+ File, chocolatey.dll, has a different computed hash than specified in manifest.**

ENGLISH:
```
PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1038.0 built by: NETFXREL2
	clr.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET
	Application url			: http://boxstarter.org/launch/Application%20Files/Boxstarter.WebLaunch_2_6_25_0/Boxstarter.WebLaunch.exe.manifest
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET

IDENTITIES
	Deployment Identity		: Boxstarter.WebLaunch.application, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil
	Application Identity		: Boxstarter.WebLaunch.exe, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Online only application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1 resulted in exception. Following failure messages were detected:
		+ File, chocolatey.dll, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [18/12/2015 09:35:12] : Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1 has started.
	* [18/12/2015 09:35:13] : Processing of deployment manifest has successfully completed.
	* [18/12/2015 09:35:13] : Installation of the application has started.
	* [18/12/2015 09:35:14] : Processing of application manifest has successfully completed.
	* [18/12/2015 09:35:15] : Found compatible runtime version 2.0.50727.
	* [18/12/2015 09:35:15] : Detecting dependent assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil using Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
	* [18/12/2015 09:35:15] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [18/12/2015 09:35:15] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [18/12/2015 09:35:31] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, chocolatey.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

GERMAN WIN7:
```
INFO ZUR PLATTFORMVERSION
	Windows 			: 6.1.7600.0 (Win32NT)
	Common Language Runtime 	: 2.0.50727.4927
	System.Deployment.dll 		: 2.0.50727.4927 (NetFXspW7.050727-4900)
	mscorwks.dll 			: 2.0.50727.4927 (NetFXspW7.050727-4900)
	dfdll.dll 			: 2.0.50727.4927 (NetFXspW7.050727-4900)
	dfshim.dll 			: 2.0.50727.4927 (NetFXspW7.050727-4900)

QUELLEN
	Bereitstellungs-URL			: http://boxstarter.org/package/nr/url?teamviewer
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET
	Anwendungs-URL			: http://boxstarter.org/launch/Application%20Files/Boxstarter.WebLaunch_2_6_25_0/Boxstarter.WebLaunch.exe.manifest
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET

IDENTITÄTEN
	Bereitstellungsidentität		: Boxstarter.WebLaunch.application, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil
	Anwendungsidentität		: Boxstarter.WebLaunch.exe, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil, type=win32

ZUSAMMENFASSUNG FÜR ANWENDUNG
	* Reine Onlineanwendung.
	* Parameter für Vertrauensstellungs-URL ist festgelegt.
FEHLERZUSAMMENFASSUNG
	Es folgt eine Zusammenfassung der Fehler. Details zu diesen Fehlern werden später im Protokoll aufgelistet.
	* Die Aktivierung von http://boxstarter.org/package/nr/url?teamviewer führte zu einer Ausnahme. Folgende Fehlermeldungen wurden entdeckt:
		+ Die Datei 'chocolatey.dll' hat einen anderen berechneten Hash, als im Manifest angegeben ist.

FEHLERZUSAMMENFASSUNG FÜR DIE SPEICHERTRANSAKTION DER KOMPONENTE
	Es wurde kein Transaktionsfehler festgestellt.

WARNUNGEN
	Während dieses Vorgangs gab es keine Warnungen.

FORTSCHRITTSSTATUS DES VORGANGS
	* [18.12.2015 09:33:26] : Die Aktivierung von http://boxstarter.org/package/nr/url?teamviewer wurde gestartet.
	* [18.12.2015 09:33:34] : Das Verarbeiten des Bereitstellungsmanifestes wurde erfolgreich abgeschlossen.
	* [18.12.2015 09:33:34] : Die Installation der Anwendung wurde gestartet.
	* [18.12.2015 09:33:35] : Das Verarbeiten des Anwendungsmanifestes wurde erfolgreich abgeschlossen.
	* [18.12.2015 09:33:37] : Die Anforderung der Vertrauensstellung und die Ermittlung der Plattform sind abgeschlossen.

FEHLERDETAILS
	Folgende Fehler wurden bei diesem Vorgang entdeckt.
	* [18.12.2015 09:34:11] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Die Datei 'chocolatey.dll' hat einen anderen berechneten Hash, als im Manifest angegeben ist.
		- Quelle: System.Deployment
		- Stapelüberwachung:
			bei System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			bei System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			bei System.Deployment.Application.ComponentVerifier.FileComponent.Verify()
			bei System.Deployment.Application.ComponentVerifier.VerifyComponents()
			bei System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			bei System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			bei System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			bei System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			bei System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

DETAILS ZUR SPEICHERTRANSAKTION DER KOMPONENTE
	Es sind keine Transaktionsinformationen verfügbar.


```

DUTCH WIN10:
```
INFO PLATFORMVERSIE
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1038.0 built by: NETFXREL2
	clr.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

BRONNEN
	Implementatie-url			: http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET
	Toepassing-url			: http://boxstarter.org/launch/Application%20Files/Boxstarter.WebLaunch_2_6_25_0/Boxstarter.WebLaunch.exe.manifest
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET

IDENTITEITEN
	Implementatie-identiteit		: Boxstarter.WebLaunch.application, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil
	Toepassingsidentiteit		: Boxstarter.WebLaunch.exe, Version=2.6.25.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil, type=win32

TOEPASSINGSSAMENVATTING
	* Toepassing voor alleen on line gebruik.
	* Parameter voor vertrouwens-url is ingesteld.
FOUTSAMENVATTING
	Hieronder ziet u een overzicht van de fouten. Verderop in het logboek vindt u nadere details over deze fouten.
	* Activering van http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1 heeft tot een uitzondering geleid. De volgende berichten voor mislukte acties zijn aangetroffen:
		+ Het bestand, chocolatey.dll, heeft een andere berekende hash dan de hash die is opgegeven in het manifest.

SAMENVATTING MISLUKTE TRANSACTIES ONDERDELENARCHIEF
	Er zijn geen transactiefouten aangetroffen.

WAARSCHUWINGEN
	Er werden geen waarschuwingen weergegeven bij deze bewerking.

VOORTGANGSSTATUS BEWERKING
	* [18-12-2015 10:31:38] : De activering van http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1&https://gist.githubusercontent.com/Proxx/d8dd79d4b6f39a41f2ef/raw/a0719300fb32d1d1c45e116e72775b7434a88c66/BoxStarter.ps1 is gestart.
	* [18-12-2015 10:31:39] : Verwerking van het implementatiemanifest is voltooid.
	* [18-12-2015 10:31:39] : De installatie van de toepassing is gestart.
	* [18-12-2015 10:31:40] : Verwerking van het toepassingsmanifest is voltooid.
	* [18-12-2015 10:32:08] : Compatibele runtimeversie 2.0.50727 gevonden.
	* [18-12-2015 10:32:08] : Afhankelijke assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil gedetecteerd met Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
	* [18-12-2015 10:32:08] : Afhankelijke assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil gedetecteerd met System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [18-12-2015 10:32:08] : Aanvragen van vertrouwen en detectie van platform zijn voltooid.

FOUTDETAILS
	De volgende fouten zijn aangetroffen bij deze bewerking.
	* [18-12-2015 10:33:16] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Het bestand, chocolatey.dll, heeft een andere berekende hash dan de hash die is opgegeven in het manifest.
		- Bron: System.Deployment
		- Stack-tracering:
			bij System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			bij System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			bij System.Deployment.Application.ComponentVerifier.VerifyComponents()
			bij System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			bij System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			bij System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			bij System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			bij System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

TRANSACTIEDETAILS ONDERDELENARCHIEF
	Er is geen transactie-informatie beschikbaar.

```

**Comment by mwrock** [comment]
Weird. I am unable to reproduce.

**Comment by Proxx** [comment]
strange i'm trying on 3 different machines, one HP8100, Lenovo Thinkpad, and a brand new Dell XPS13

**Comment by Proxx** [comment]
Found the problem!
the company's Antivirus (F-Secure Client Security v12.0) has a function called DeepGuard 
when disabling that all works fine!

**Comment by mwrock** [comment]
I wonder if it is at all related to being outside the united states. I'm not sure exactly how the click-once hashes work. I know it uses SHA1 but then it must do some sort of other conversion because the sha1.

I am curious, did these boxes previously run the older versions of boxstarter or are they clean machines? The reason I ask is because I once had an issue where i had to clear the machine's application cache and then redownload boxstarter.

**Comment by mwrock** [comment]
ah. whew. thanks for letting me know!
